########################################################
###datasource
########################################################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distributedlock
    username: root
    password: root
########################################################
###log
########################################################
logging:
      level:
        com.hzp.work.module.distributedlock.mapper: debug